-- AlterTable
ALTER TABLE `user` ADD COLUMN `draws` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `elo` INTEGER NOT NULL DEFAULT 1000,
    ADD COLUMN `losses` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `wins` INTEGER NOT NULL DEFAULT 0;
